#!/bin/bash

git clone git@github.com:jaz303/presto-node.git
git clone git@github.com:jaz303/presto.git
git clone git@github.com:jaz303/presto-examples.git

cd presto-node
# TODO: check out correct branch
./configure
make

cd ..
./npm install node-gyp

